import { subDays, subMonths, subWeeks } from 'date-fns'

export type MockClient = {
  id: string
  name: string
  phone: string
  email?: string
  total_visits: number
  total_spent: number
  last_visit_at: string
  created_at: string
  notes?: string
  segment: 'vip' | 'frequent' | 'new' | 'inactive'
  churn_risk?: number // 0-100
  loyalty_progress?: number // 0-100
  avg_days_between_visits?: number
  favorite_service?: string
  referrals?: number
}

const today = new Date()

export const mockClients: MockClient[] = [
  // VIP Clients (12)
  {
    id: '1',
    name: 'Carlos Rodríguez',
    phone: '87175866',
    email: 'carlos.r@email.com',
    total_visits: 24,
    total_spent: 180000,
    last_visit_at: subDays(today, 3).toISOString(),
    created_at: subMonths(today, 14).toISOString(),
    notes: 'Prefiere corte clásico con fade. Siempre puntual.',
    segment: 'vip',
    churn_risk: 5,
    loyalty_progress: 95,
    avg_days_between_visits: 14,
    favorite_service: 'Corte + Barba',
    referrals: 5,
  },
  {
    id: '2',
    name: 'José Martínez',
    phone: '88234567',
    email: 'jose.m@email.com',
    total_visits: 18,
    total_spent: 135000,
    last_visit_at: subDays(today, 7).toISOString(),
    created_at: subMonths(today, 10).toISOString(),
    segment: 'vip',
    churn_risk: 15,
    loyalty_progress: 85,
    avg_days_between_visits: 16,
    favorite_service: 'Corte Premium',
    referrals: 3,
  },
  {
    id: '3',
    name: 'Miguel Ángel Soto',
    phone: '89345678',
    email: 'miguel.soto@email.com',
    total_visits: 15,
    total_spent: 120000,
    last_visit_at: subDays(today, 5).toISOString(),
    created_at: subMonths(today, 9).toISOString(),
    notes: 'Le gusta el café mientras espera',
    segment: 'vip',
    churn_risk: 8,
    loyalty_progress: 90,
    avg_days_between_visits: 18,
    favorite_service: 'Corte + Afeitado',
    referrals: 2,
  },
  {
    id: '4',
    name: 'Alejandro Vargas',
    phone: '87456789',
    total_visits: 14,
    total_spent: 98000,
    last_visit_at: subDays(today, 10).toISOString(),
    created_at: subMonths(today, 8).toISOString(),
    segment: 'vip',
    churn_risk: 20,
    loyalty_progress: 75,
    avg_days_between_visits: 17,
    favorite_service: 'Corte Moderno',
    referrals: 1,
  },
  {
    id: '5',
    name: 'Fernando López',
    phone: '88567890',
    email: 'fer.lopez@email.com',
    total_visits: 12,
    total_spent: 96000,
    last_visit_at: subDays(today, 2).toISOString(),
    created_at: subMonths(today, 7).toISOString(),
    segment: 'vip',
    churn_risk: 5,
    loyalty_progress: 92,
    avg_days_between_visits: 15,
    favorite_service: 'Corte + Barba',
    referrals: 4,
  },
  {
    id: '6',
    name: 'Ricardo Hernández',
    phone: '89678901',
    total_visits: 11,
    total_spent: 88000,
    last_visit_at: subDays(today, 12).toISOString(),
    created_at: subMonths(today, 6).toISOString(),
    segment: 'vip',
    churn_risk: 25,
    loyalty_progress: 70,
    avg_days_between_visits: 16,
    favorite_service: 'Corte Clásico',
    referrals: 2,
  },
  {
    id: '7',
    name: 'Daniel Castro',
    phone: '87789012',
    email: 'daniel.c@email.com',
    total_visits: 10,
    total_spent: 85000,
    last_visit_at: subDays(today, 6).toISOString(),
    created_at: subMonths(today, 5).toISOString(),
    segment: 'vip',
    churn_risk: 10,
    loyalty_progress: 88,
    avg_days_between_visits: 14,
    favorite_service: 'Corte + Ceja',
    referrals: 3,
  },
  {
    id: '8',
    name: 'Andrés Ramírez',
    phone: '88890123',
    total_visits: 9,
    total_spent: 72000,
    last_visit_at: subDays(today, 15).toISOString(),
    created_at: subMonths(today, 5).toISOString(),
    segment: 'vip',
    churn_risk: 30,
    loyalty_progress: 65,
    avg_days_between_visits: 17,
    favorite_service: 'Corte Premium',
    referrals: 1,
  },
  {
    id: '9',
    name: 'Pablo Morales',
    phone: '89901234',
    email: 'pablo.m@email.com',
    total_visits: 8,
    total_spent: 68000,
    last_visit_at: subDays(today, 4).toISOString(),
    created_at: subMonths(today, 4).toISOString(),
    segment: 'vip',
    churn_risk: 8,
    loyalty_progress: 90,
    avg_days_between_visits: 15,
    favorite_service: 'Corte + Barba',
    referrals: 2,
  },
  {
    id: '10',
    name: 'Luis Jiménez',
    phone: '87012345',
    total_visits: 7,
    total_spent: 63000,
    last_visit_at: subDays(today, 18).toISOString(),
    created_at: subMonths(today, 4).toISOString(),
    segment: 'vip',
    churn_risk: 35,
    loyalty_progress: 60,
    avg_days_between_visits: 18,
    favorite_service: 'Corte Moderno',
    referrals: 1,
  },
  {
    id: '11',
    name: 'Roberto Díaz',
    phone: '88123456',
    email: 'roberto.d@email.com',
    total_visits: 6,
    total_spent: 54000,
    last_visit_at: subDays(today, 8).toISOString(),
    created_at: subMonths(today, 3).toISOString(),
    segment: 'vip',
    churn_risk: 12,
    loyalty_progress: 82,
    avg_days_between_visits: 15,
    favorite_service: 'Corte + Afeitado',
    referrals: 2,
  },
  {
    id: '12',
    name: 'Sergio Navarro',
    phone: '89234567',
    total_visits: 6,
    total_spent: 51000,
    last_visit_at: subDays(today, 9).toISOString(),
    created_at: subMonths(today, 3).toISOString(),
    segment: 'vip',
    churn_risk: 15,
    loyalty_progress: 78,
    avg_days_between_visits: 16,
    favorite_service: 'Corte Premium',
    referrals: 1,
  },

  // Frequent Clients (35)
  {
    id: '13',
    name: 'Juan Pérez',
    phone: '87345678',
    email: 'juan.p@email.com',
    total_visits: 4,
    total_spent: 32000,
    last_visit_at: subDays(today, 5).toISOString(),
    created_at: subMonths(today, 2).toISOString(),
    segment: 'frequent',
    churn_risk: 10,
    loyalty_progress: 65,
    avg_days_between_visits: 14,
    favorite_service: 'Corte Regular',
    referrals: 1,
  },
  {
    id: '14',
    name: 'Pedro Gómez',
    phone: '88456789',
    total_visits: 4,
    total_spent: 30000,
    last_visit_at: subDays(today, 11).toISOString(),
    created_at: subMonths(today, 2).toISOString(),
    segment: 'frequent',
    churn_risk: 22,
    loyalty_progress: 58,
    avg_days_between_visits: 15,
    favorite_service: 'Corte Simple',
  },
  {
    id: '15',
    name: 'Antonio Ruiz',
    phone: '89567890',
    email: 'antonio.r@email.com',
    total_visits: 3,
    total_spent: 24000,
    last_visit_at: subDays(today, 7).toISOString(),
    created_at: subWeeks(today, 7).toISOString(),
    segment: 'frequent',
    churn_risk: 15,
    loyalty_progress: 62,
    avg_days_between_visits: 16,
    favorite_service: 'Corte Regular',
  },
  {
    id: '16',
    name: 'Francisco Torres',
    phone: '87678901',
    total_visits: 3,
    total_spent: 22500,
    last_visit_at: subDays(today, 14).toISOString(),
    created_at: subWeeks(today, 7).toISOString(),
    segment: 'frequent',
    churn_risk: 28,
    loyalty_progress: 52,
    avg_days_between_visits: 16,
    favorite_service: 'Corte Simple',
  },
  // ... (repeating pattern for remaining frequent clients)
  ...Array.from({ length: 31 }, (_, i) => ({
    id: `${17 + i}`,
    name: `Cliente Frecuente ${i + 5}`,
    phone: `8${8000000 + i * 111111}`,
    email: i % 3 === 0 ? `frecuente${i + 5}@email.com` : undefined,
    total_visits: 3 + (i % 2),
    total_spent: 21000 + i * 500,
    last_visit_at: subDays(today, 6 + (i % 10)).toISOString(),
    created_at: subWeeks(today, 6 + (i % 4)).toISOString(),
    segment: 'frequent' as const,
    churn_risk: 10 + (i % 20),
    loyalty_progress: 55 + (i % 15),
    avg_days_between_visits: 14 + (i % 5),
    favorite_service: i % 2 === 0 ? 'Corte Regular' : 'Corte Simple',
    referrals: i % 5 === 0 ? 1 : undefined,
  })),

  // New Clients (45)
  {
    id: '48',
    name: 'Nuevo Cliente 1',
    phone: '87111111',
    email: 'nuevo1@email.com',
    total_visits: 2,
    total_spent: 16000,
    last_visit_at: subDays(today, 3).toISOString(),
    created_at: subWeeks(today, 3).toISOString(),
    segment: 'new',
    churn_risk: 18,
    loyalty_progress: 35,
    avg_days_between_visits: 10,
    favorite_service: 'Corte Simple',
  },
  {
    id: '49',
    name: 'Nuevo Cliente 2',
    phone: '88222222',
    total_visits: 1,
    total_spent: 8000,
    last_visit_at: subDays(today, 5).toISOString(),
    created_at: subDays(today, 5).toISOString(),
    segment: 'new',
    churn_risk: 25,
    loyalty_progress: 20,
    favorite_service: 'Corte Regular',
  },
  ...Array.from({ length: 43 }, (_, i) => ({
    id: `${50 + i}`,
    name: `Nuevo Cliente ${i + 3}`,
    phone: `8${8333333 + i * 11111}`,
    email: i % 4 === 0 ? `nuevo${i + 3}@email.com` : undefined,
    total_visits: 1 + (i % 2),
    total_spent: 7500 + i * 500,
    last_visit_at: subDays(today, 2 + (i % 8)).toISOString(),
    created_at: subDays(today, 2 + (i % 15)).toISOString(),
    segment: 'new' as const,
    churn_risk: 20 + (i % 15),
    loyalty_progress: 15 + (i % 25),
    avg_days_between_visits: i % 2 === 0 ? 7 : undefined,
    favorite_service: i % 2 === 0 ? 'Corte Simple' : 'Corte Regular',
  })),

  // Inactive Clients (58)
  {
    id: '93',
    name: 'Inactivo Cliente 1',
    phone: '87999999',
    email: 'inactivo1@email.com',
    total_visits: 5,
    total_spent: 40000,
    last_visit_at: subDays(today, 45).toISOString(),
    created_at: subMonths(today, 6).toISOString(),
    segment: 'inactive',
    churn_risk: 75,
    loyalty_progress: 30,
    avg_days_between_visits: 22,
    favorite_service: 'Corte Regular',
    referrals: 1,
  },
  ...Array.from({ length: 57 }, (_, i) => ({
    id: `${94 + i}`,
    name: `Inactivo Cliente ${i + 2}`,
    phone: `8${7888888 + i * 11111}`,
    email: i % 5 === 0 ? `inactivo${i + 2}@email.com` : undefined,
    total_visits: 2 + (i % 8),
    total_spent: 15000 + i * 1000,
    last_visit_at: subDays(today, 31 + (i % 60)).toISOString(),
    created_at: subMonths(today, 3 + (i % 10)).toISOString(),
    segment: 'inactive' as const,
    churn_risk: 65 + (i % 30),
    loyalty_progress: 10 + (i % 25),
    avg_days_between_visits: 20 + (i % 15),
    favorite_service: i % 2 === 0 ? 'Corte Regular' : 'Corte Simple',
    referrals: i % 10 === 0 ? 1 : undefined,
  })),
]

// Stats calculados
export const mockStats = {
  totalClients: mockClients.length,
  newThisMonth: mockClients.filter((c) => {
    const created = new Date(c.created_at)
    const monthAgo = subMonths(today, 1)
    return created > monthAgo
  }).length,
  activeClients: mockClients.filter((c) => {
    const lastVisit = new Date(c.last_visit_at)
    const thirtyDaysAgo = subDays(today, 30)
    return lastVisit > thirtyDaysAgo
  }).length,
  totalRevenue: mockClients.reduce((sum, c) => sum + c.total_spent, 0),
  avgValue: mockClients.reduce((sum, c) => sum + c.total_spent, 0) / mockClients.length,
  segments: {
    vip: mockClients.filter((c) => c.segment === 'vip').length,
    frequent: mockClients.filter((c) => c.segment === 'frequent').length,
    new: mockClients.filter((c) => c.segment === 'new').length,
    inactive: mockClients.filter((c) => c.segment === 'inactive').length,
  },
  churnRisk: {
    high: mockClients.filter((c) => (c.churn_risk || 0) >= 50).length,
    medium: mockClients.filter((c) => (c.churn_risk || 0) >= 25 && (c.churn_risk || 0) < 50).length,
    low: mockClients.filter((c) => (c.churn_risk || 0) < 25).length,
  },
  topClient: mockClients.reduce((top, c) => (c.total_spent > top.total_spent ? c : top)),
}

// Monthly revenue data for charts (last 6 months)
export const mockRevenueData = Array.from({ length: 6 }, (_, i) => {
  const month = subMonths(today, 5 - i)
  const monthName = month.toLocaleDateString('es', { month: 'short' })
  return {
    month: monthName,
    revenue: 120000 + Math.floor(Math.random() * 80000),
    clients: 30 + Math.floor(Math.random() * 20),
  }
})

// Visit frequency distribution
export const mockVisitFrequency = [
  { range: '1-7 días', count: 45, color: '#22C55E' },
  { range: '8-14 días', count: 38, color: '#3B82F6' },
  { range: '15-21 días', count: 28, color: '#F59E0B' },
  { range: '22-30 días', count: 18, color: '#EF4444' },
  { range: '30+ días', count: 21, color: '#6B7280' },
]
