import type { Metadata } from 'next'
import { HeroSection } from '@/components/landing/hero-section'
import { FeaturesSection } from '@/components/landing/features-section'
import { TestimonialsSection } from '@/components/landing/testimonials-section'
import { PricingSection } from '@/components/landing/pricing-section'
import { FinalCTA, Footer } from '@/components/landing/footer'
import { LandingNavbar, MobileFloatingCTA } from '@/components/landing/landing-navbar'

export const metadata: Metadata = {
  title: 'BarberApp - Sistema de Gestion para Barberias | Agenda, Clientes y Pagos',
  description:
    'Gestiona tu barberia con el sistema mas completo: agenda inteligente, clientes, reservas online, analiticas y mas. 7 dias de prueba gratis. Sin tarjeta de credito.',
  keywords: [
    'barberia',
    'agenda barberia',
    'sistema de reservas',
    'gestion de clientes',
    'barbershop software',
    'agenda online',
    'Costa Rica',
    'barberia profesional',
    'reservas online',
    'software para barberias',
  ],
  authors: [{ name: 'BarberApp' }],
  creator: 'BarberApp',
  publisher: 'BarberApp',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://barberapp.com'),
  openGraph: {
    title: 'BarberApp - Sistema de Gestion para Barberias',
    description:
      'Gestiona tu barberia profesionalmente: agenda inteligente, clientes, reservas online y analiticas. Prueba gratis por 7 dias.',
    url: 'https://barberapp.com',
    siteName: 'BarberApp',
    // OG image auto-generated by src/app/opengraph-image.tsx
    locale: 'es_CR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BarberApp - Sistema de Gestion para Barberias',
    description:
      'Gestiona tu barberia profesionalmente. Agenda, clientes, reservas online. Prueba gratis 7 dias.',
    // Twitter image auto-discovered from opengraph-image.tsx
    creator: '@barberapp',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // verification: { google: 'ADD_REAL_CODE_FROM_SEARCH_CONSOLE' },
  alternates: {
    canonical: 'https://barberapp.com',
  },
}

export default function Home() {
  return (
    <>
      <LandingNavbar />
      <HeroSection />
      <FeaturesSection />
      <TestimonialsSection />
      <PricingSection />
      <FinalCTA />
      <Footer />
      <MobileFloatingCTA />
    </>
  )
}
